=== Baltasarq/JSpeccy/src/schema/JSpeccy.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://xml.netbeans.org/schema/JSpeccy"
    xmlns:tns="http://xml.netbeans.org/schema/JSpeccy"
    elementFormDefault="qualified">
    <xsd:element name="JSpeccySettings" type="tns:JSpeccySettingsType"/>
    <xsd:complexType name="SpectrumType">
        <xsd:sequence>
            <xsd:element name="Issue2" default="false" type="xsd:boolean"/>
            <xsd:element name="AYEnabled48k" type="xsd:boolean" default="false"/>
            <xsd:element name="soundEnabled" type="xsd:boolean" default="true"/>
            <xsd:element name="loadingNoise" type="xsd:boolean" default="true"/>
            <xsd:element name="ULAplus" type="xsd:boolean" default="false"/>
            <xsd:element name="defaultModel" default="0" form="qualified">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="4"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="framesInt" form="qualified" default="2">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="10"/>
                        <xsd:minInclusive value="2"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="MemoryType">
        <xsd:sequence>
            <xsd:element name="RomsDirectory" type="xsd:string"/>
            <xsd:element name="Rom48k" type="xsd:string" default="spectrum.rom"/>
            <xsd:element name="Rom128k0" type="xsd:string" default="128-0.rom"/>
            <xsd:element name="Rom128k1" type="xsd:string" default="128-1.rom"/>
            <xsd:element name="RomPlus20" type="xsd:string" default="plus2-0.rom"/>
            <xsd:element name="RomPlus21" type="xsd:string" default="plus2-1.rom"/>
            <xsd:element name="RomPlus30" type="xsd:string" default="plus3-0.rom"/>
            <xsd:element name="RomPlus31" type="xsd:string" default="plus3-1.rom"/>
            <xsd:element name="RomPlus32" type="xsd:string" default="plus3-2.rom"/>
            <xsd:element name="RomPlus33" type="xsd:string" default="plus3-3.rom"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="TapeType">
        <xsd:sequence>
            <xsd:element name="flashload" type="xsd:boolean" default="true"/>
            <xsd:element name="accelerateLoading" type="xsd:boolean" default="true"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="KeyboardJoystickType">
        <xsd:sequence>
            <xsd:element name="JoystickModel" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="4"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="AY8912Type">
        <xsd:sequence>
            <xsd:element name="soundMode" default="0">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:maxInclusive value="2"/>
                        <xsd:minInclusive value="0"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="JSpeccySettingsType">
        <xsd:sequence>
            <xsd:element name="SpectrumSettings" type="tns:SpectrumType"/>
            <xsd:element name="MemorySettings" type="tns:MemoryType"/>
            <xsd:element name="TapeSettings" type="tns:TapeType"/>
            <xsd:element name="KeyboardJoystickSettings" type="tns:KeyboardJoystickType"/>
            <xsd:element name="AY8912Settings" type="tns:AY8912Type"/>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Baltasarq/JSpeccy/src/schema/JSpeccy.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<!--
    Document   : JSpeccy.xml
    Created on : 4 de septiembre de 2010, 12:04
    Author     : jsanchez
    Description:
        Purpose of the document follows.
-->

<ns0:JSpeccySettings  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns0='http://xml.netbeans.org/schema/JSpeccy'
   xsi:schemaLocation='http://xml.netbeans.org/schema/JSpeccy JSpeccy.xsd'>
    <ns0:SpectrumSettings>
        <ns0:Issue2>false</ns0:Issue2>
        <ns0:AYEnabled48k>false</ns0:AYEnabled48k>
        <ns0:soundEnabled>true</ns0:soundEnabled>
        <ns0:loadingNoise>true</ns0:loadingNoise>
        <ns0:ULAplus>false</ns0:ULAplus>
        <ns0:defaultModel>0</ns0:defaultModel>
    </ns0:SpectrumSettings>
    <ns0:MemorySettings>
        <ns0:RomsDirectory></ns0:RomsDirectory>
        <ns0:Rom48k>spectrum.rom</ns0:Rom48k>
        <ns0:Rom128k0>128-0.rom</ns0:Rom128k0>
        <ns0:Rom128k1>128-1.rom</ns0:Rom128k1>
        <ns0:RomPlus20>plus2-0.rom</ns0:RomPlus20>
        <ns0:RomPlus21>plus2-1.rom</ns0:RomPlus21>
        <ns0:RomPlus30>plus3-0.rom</ns0:RomPlus30>
        <ns0:RomPlus31>plus3-1.rom</ns0:RomPlus31>
        <ns0:RomPlus32>plus3-2.rom</ns0:RomPlus32>
        <ns0:RomPlus33>plus3-3.rom</ns0:RomPlus33>
    </ns0:MemorySettings>
    <ns0:TapeSettings>
        <ns0:flashload>true</ns0:flashload>
        <ns0:accelerateLoading>true</ns0:accelerateLoading>
    </ns0:TapeSettings>
    <ns0:KeyboardJoystickSettings>
        <ns0:JoystickModel>0</ns0:JoystickModel>
    </ns0:KeyboardJoystickSettings>
    <ns0:AY8912Settings>
        <ns0:soundMode>0</ns0:soundMode>
    </ns0:AY8912Settings>

</ns0:JSpeccySettings>
